using System.Collections;
using System.Collections.Generic;
using UnityEngine;

//tilemapæœ‰ç¼éš™ï¼Œå¯¼è‡´walljumpæœ‰æ—¶ä¼šå¾€ä¸‹è·³ï¼Œä½¿ç”¨æ•´ä½“çš„ç¢°æ’æ—¶åˆ™ä¸ä¼šå‘ç”Ÿ?????ä¸æ˜¯ï¼Œæ•´ä½“çš„ä¹Ÿä¼š å½“åœ¨è·³è·ƒåæ¸…é™¤jumpbufferTimecounterè®¡æ•°æ—¶ä¼šå‘ç”Ÿ
//ä¸Šé¢æ˜¯æ”¾å±ï¼ŒğŸ‘´æ˜¯å‚»ç‹—

//åªå…è®¸å·¦å³å†²åˆºï¼Ÿå…«å‘å†²åˆºï¼Ÿ

//TODO:Dash
//TODO:jumpBufferTimeéœ€è¦æ”¹è¿›
//é å¢™é•¿è·³åº”å½“ä¸å—å¢™å½±å“
//æ»‘å¢™çš„åˆ¤å®šè¿˜éœ€è¦è€ƒè™‘ï¼Œ
//TODO:äºŒæ®µè·³æ”¹ä¸ºjump+airJump,ä¸æ˜¯jump+jump //done
//TODO:Dashæ—¶æŠŠç¢°æ’ç›’ç¼©å°   //done ä¿®æ”¹transformä¹Ÿä¼šä¿®æ”¹ç¢°æ’ç›’ï¼Œæ‰€ä»¥ç›´æ¥æ”¹transformäº†ï¼Œå¯èƒ½æœ‰é—®é¢˜
//TODO:Dash+Jump    ä¼šæå‰é€€å‡ºå†²åˆºçŠ¶æ€  //done
//ä¸Šé¢éƒ½æ²¡æ€ä¹ˆä»”ç»†æµ‹è¯•ï¼Œç®¡ä»–å‘¢

//TODOï¼šæœ‰æ—¶å€™wallJumpä¼šå¾€ä¸‹è·³ï¼Œä¸çŸ¥é“ä»€ä¹ˆåŸå› 


//TODOï¼šdown+dash+jump  é‡è¦
//TODOï¼šè¦è®©æ‰‹æ„Ÿæœ‰apexçš„æ„Ÿè§‰ï¼Œä½ æ‡‚å—ï¼Ÿ
//ä¸æ‡‚ï¼Œæ·¦éœ–é‡,ALmovement

//TODO: ç®€å•çš„æ”»å‡»ç³»ç»Ÿ
//åœ¨åšäº†

//TODO: æ—‹è½¬è·³è·ƒ
//ï¼Ÿæ—¶é—´å¤ªä¹…äº†ï¼Œå¿˜äº†è‡ªå·±å†™çš„å•¥ï¼Œä¸‹æ¬¡å†™æ¸…æ¥šç‚¹


//TODO:ä¸ŠæŒ‘æ²¡åšå¥½ï¼Œç›®å‰å¾ˆæ‹‰è·¨ï¼Œå°±æ˜¯æŒ‰é”®è§¦å‘ï¼Œç»™ä¸ªå‘ä¸Šçš„åŠ›ï¼Œå¼€ä¸ªåç¨‹ï¼šä¸€å¼€å§‹å¼€boolè¿‡æ®µæ—¶é—´å…³boolï¼Œæ‰“å¼€ä¼¤å®³boxï¼›åŠ¨ç”»é‚£è¾¹æ£€æµ‹boolï¼Œæ’­æ”¾åŠ¨ç”»ï¼Œæ’­æ”¾å®Œå…³é—­ä¼¤å®³box
//å›å¤ï¼šç›®å‰ï¼Œæ­¦å™¨ç±»å†™äº†ï¼Œä½œä¸ºä¸€ä¸ªæˆå‘˜å˜é‡ï¼Œä¼šåœ¨åˆå§‹åŒ–æ—¶èµ‹å€¼ï¼ˆä¸æŒ‡æ˜è„šæœ¬æ—¶éƒ½æ˜¯æŒ‡æœ¬è„šæœ¬ï¼‰ã€‚æ¯æ¬¡updateéƒ½ä¼šè°ƒç”¨é‚£è¾¹çš„MyUpdateï¼ˆï¼‰
//å…¶å®å°±æ˜¯æŠŠæ­¦å™¨éƒ¨åˆ†çš„é€»è¾‘å†™åˆ°äº†æ­¦å™¨å“ªé‡Œï¼Œæ„Ÿè§‰ä¸å¤ªè¡Œ
//ç„¶åæ²¡ç”¨åç¨‹äº†ï¼Œç”¨äº†è‡ªå·±å†™çš„TimeCounterå°±æ˜¯Length+Counterï¼Œé›†æˆäº†ä¸€ä¸‹ï¼Œæ–¹ä¾¿ä¸€ç‚¹ã€‚
//ä¼ åˆ°æ­¦å™¨ç±»é‚£è¾¹çš„æœ‰StateManagerï¼ŒRigidbody2Dï¼Œæ­¦å™¨çš„hitboxçš„æ¸¸æˆå¯¹è±¡ã€‚
//æ„Ÿè§‰è¿™ä¸ªçŠ¶æ€æœºéœ€è¦åšä¸ªå•ä¾‹æ¨¡å¼ï¼Ÿæ²¡æœ‰å¤šçº¿ç¨‹å§ï¼Ÿ

//TODOï¼šæ‘„åƒæœºéœ‡åŠ¨æ—¶ä¼šå¯¼è‡´æ•Œäººé—ªçƒï¼Œä¼°è®¡æ˜¯zè½´çš„éœ‡è¡

//ä¸åŒçš„æ‹›å¼ï¼Œæ•Œäººä¸åŒçš„å—å‡»ï¼Œä¸ŠæŒ‘è‚¯å®šè¦å‘ä¸Šå‡»é£æ•Œäººï¼Œ
//é‚£ä¹ˆåŸæœ¬çš„ï¼Œæ­¦å™¨è°ƒç”¨æ•Œäººçš„å—å‡»å‡½æ•°ï¼Œè¿˜éœ€è¦ä¼ æ›´å¤šçš„å‚æ•°
//åŠ¨ä½œä¼˜å…ˆçº§ï¼ˆéœ¸ä½“ï¼‰

[RequireComponent(typeof(Rigidbody2D))]
public class Movement : MonoBehaviour
{
    public int health = 10;

    private TimePoint hurtTP;

    private int moveModel = 0;
    public StateManager SM;
    public MySword weapon;
    private float transformTime = 0.3f;
    private float transformTImeCounter = 0;

    private Collider2D coll;
    public Rigidbody2D rb;
    private SpriteRenderer SR;
    private Cinemachine.CinemachineImpulseSource MyInpulse;

    public LayerMask groundLayer;

    private Vector2 spSize;
    public int side = 1;   //æ ¹æ®è¾“å…¥å†³å®šçš„side**


    public int speed = 5;
    public int airWalkSpeed = 5;
    public int jumpForce = 7;
    public int dashSpeed = 10;
    public int dashJumpForce = 10;
    public int airJumpForce = 10;
    public float wallSlideSpeed = 5;
    public float wallJumpSpeed = 10;
    
    public float jumpTime = 0.3f;
    [SerializeField] private float jumpTimeCounter;

    public float graceTime = 0.1f;  //å…è®¸çš„åœŸç‹¼æ—¶é—´
    [SerializeField] private float graceTimeCounter; //åœŸç‹¼æ—¶é—´è®¡æ—¶

    public float jumpBufferTime = 0.1f; //è·³è·ƒçš„è¾“å…¥ç¼“å†²æ—¶é—´
    [SerializeField] private float jumpBufferTimeCounter; //è·³è·ƒçš„è¾“å…¥ç¼“å†²è®¡æ—¶
    
    [SerializeField] bool downPressed = false;

    [SerializeField] bool jumpPressed = false;
    [SerializeField] int airJumpCounter = 1;   //å…è®¸è·³è·ƒæ¬¡æ•°
    [SerializeField] bool airJumpPressed = false;   //ç©ºä¸­è·³è·ƒ
    [SerializeField] bool wallJumpPressed = false;
    [SerializeField] bool hasDash = false;
    [SerializeField] bool dashJumpPressed = false;
    bool dashPressed = false;


    //çŠ¶æ€
    [SerializeField] bool onGround = false;
    [SerializeField] bool onAir = false;
    bool onWallSlide = false;
    [SerializeField] bool isJumping = false;
    [SerializeField] bool higherJump = false;

    public bool isUpChoping;
    [SerializeField] bool onWall = false;
    bool onRightWall = false;
    bool onLeftWall = false;

    bool canWalk = true;
    [SerializeField] public bool isDashing = false;

    float originalGravity;


    void Awake() 
    {
        
    }
    // Start is called before the first frame update
    void Start()
    {
        coll = GetComponent<Collider2D>();
        rb = GetComponent<Rigidbody2D>();
        SR = GetComponent<SpriteRenderer>();
        spSize = GetComponent<SpriteRenderer>().bounds.size;
        MyInpulse = GetComponent<Cinemachine.CinemachineImpulseSource>();

        originalGravity = rb.gravityScale;
        Physics2D.queriesStartInColliders = false;  //é¿å…å°„çº¿ä»å†…éƒ¨å‘å°„æ—¶æ£€æµ‹åˆ°è‡ªå·±
        string[] allState = {"onGround", "onAir", "isDashing", "isUpChoping", "isDashChoping"};
        SM = new StateManager();
        SM.Insert(allState);
        weapon = new MySword(transform.GetChild(0).gameObject, rb, SM);
        // TimeCounter hurtTC = new TimeCounter(1f);
        hurtTP = new TimePoint(1f);
        
    }

    // Update is called once per frame
    void Update()
    {
        // Debug.Log(rb.velocity);
        /*
        GetButtonDownï¼ŒæŒ‰ä¸‹è¿”å›trueï¼Œå¹¶åœ¨ä¸‹ä¸€å¸§é‡ç½®ï¼ŒåŒæ—¶é™¤éæ¾å¼€æŒ‰é”®é‡æŒ‰ï¼Œå¦åˆ™æ— æ³•è§¦å‘ä¸‹ä¸€æ¬¡è¿”å›
        æ‰€ä»¥ä¸èƒ½æ”¾fixupdateï¼Œå¯èƒ½æŒ‰äº†ä½†æ˜¯åˆåœ¨ä¸‹ä¸€å¸§è¢«é‡ç½®äº†å¯¼è‡´ç­‰äºæ²¡æŒ‰
        å¾—æ”¾åœ¨updateé¿å…è¢«é‡ç½®ï¼Œå¹¶è®¾ç½®boolå€¼ä¼ é€’ç»™fixupdate
        */
        float xRaw = Input.GetAxisRaw("Horizontal");    
        float yRaw = Input.GetAxisRaw("Vertical");
        if (Input.GetButtonDown("MM1"))
        {
            changeMoveModel(0);
            Debug.Log("change move model to model_0");
        }
        else if (Input.GetButtonDown("MM2"))
        {
            changeMoveModel(1);
            Debug.Log("change move model to model_1");
        }
        if (yRaw == -1) crouch();
        else stopCrouch();
        // else if (Input.GetKeyUp(KeyCode.DownArrow)) stopCrouch();

        //æ—§æ”»å‡»æ¨¡å—ï¼Œè¿ç§»åˆ°æ­¦å™¨äº†
        // if (Input.GetButtonDown("Attack"))
        // {
        //     if (onGround)
        //     {
        //         if (Input.GetKey(KeyCode.UpArrow))
        //         {
        //             //TODO:ä¸ŠæŒ‘
        //             upChop();
        //         }
        //         else
        //         {
        //             chop();
        //         }
        //     }
        //     else 
        //     {
        //         chop();
        //     }
            
        // }
        if (xRaw > 0){side = 1;transform.eulerAngles = new Vector3(0,0,0);}
        else if (xRaw < 0) {side = -1; transform.eulerAngles = new Vector3(0,180,0);}

        chekGround();
        if (!onGround)checkWall();

        if (Input.GetButtonDown("Jump")){jumpBufferTimeCounter = jumpBufferTime;}

        
        if (onWall)
        {
            // (Input.GetButtonDown("Jump") && xRaw>0 && onRightWall)   éœ€è¦ xRaw>0å—ï¼Ÿ éœ€è¦ç”¨è¾“å…¥ç¼“å†²å—ï¼Ÿ
            if ((jumpBufferTimeCounter > 0 && onRightWall) 
                || (jumpBufferTimeCounter > 0 && onLeftWall))
                {
                    jumpBufferTimeCounter=0;
                    wallJumpPressed = true;
                }    //å¹¶éæ»‘å¢™æ—¶è¹¬å¢™è·³
            if (rb.velocity.y < 0)onWallSlide = true;   //é å¢™ä¸‹è½æ—¶æ‰æ»‘å¢™ï¼Œé¿å…è·³åˆ°å¢™ä¸Šé©¬ä¸Šå°±æ»‘å¢™
            // if (onWallSlide && jumpBufferTimeCounter > 0)
            // {   
            //     wallJumpPressed = true;
            //     jumpBufferTimeCounter=0;
            // }  //
        }
        else{onWallSlide=false;}

        
        if(jumpBufferTimeCounter > 0)   //è·³è·ƒç¼“å†²ç”Ÿæ•ˆ
        {
            if (isDashing)  //å†²åˆºé€”ä¸­è·³è·ƒ
            {
                if (graceTimeCounter>0) //è§¦åœ°ï¼Œåˆ™dashJump
                {
                    // jumpPressed = true;  //TODO:
                    dashJumpPressed = true;
                    isJumping = true;SM.SetTrue("isJumping");
                    jumpBufferTimeCounter=0;
                    graceTimeCounter=0;              
                }
                else if (airJumpCounter>0)   //ä¸è§¦åœ°ï¼Œä¸”airJumpCounter>0
                {                           //å†²åˆºä¸­airJumpå’Œæ™®é€šçš„ä¸€æ ·
                    airJumpCounter--;
                    airJumpPressed = true;
                }
            }
            else
            {
                if (graceTimeCounter>0) //è§¦åœ°ï¼Œåˆ™Jump
                {
                    jumpPressed = true;
                    isJumping = true;SM.SetTrue("isJumping");
                    higherJump = true;
                    jumpBufferTimeCounter=0;
                    graceTimeCounter=0;
                }
                else if (airJumpCounter>0)   //ä¸è§¦åœ°ï¼Œä¸”airJumpCounter>0
                {
                    airJumpCounter--;
                    airJumpPressed = true;
                }
            }
        }
        if (higherJump)
        {
            if (Input.GetButtonUp("Jump"))higherJump = false;   //åªè¦æ¾å¼€æŒ‰é”®ç«‹åˆ»åœæ­¢ç»§ç»­ä¸Šå‡
            else    //æ²¡æœ‰æ¾å¼€æŒ‰é”®
            {
                if (jumpTimeCounter > 0)   //å¦‚æœjtc>0å°±é•¿è·³
                {
                    jumpPressed = true;
                    jumpTimeCounter -= Time.deltaTime;
                }
                else   //å¦‚æœjtc<=0ï¼Œå³é•¿è·³ç»“æŸ
                {
                    higherJump = false;
                }
            }
        }
        

        if(Input.GetButtonDown("Dash") && !hasDash)
        {
            dashPressed = true;
            StartCoroutine(stopDash(1.0f));
        }
        jumpBufferTimeCounter -= Time.deltaTime;

        weapon.MyUpdate();
    }

    //å›ºå®šé—´éš”è°ƒç”¨è¯¥å‡½æ•°ï¼Œä¸Rigidbodyçš„æ“ä½œåº”è¯¥æ”¾åœ¨è¿™é‡Œ
    void FixedUpdate()
    {
        float x = Input.GetAxis("Horizontal");
        float y = Input.GetAxis("Vertical");
        float xRaw = Input.GetAxisRaw("Horizontal");    
        float yRaw = Input.GetAxisRaw("Vertical");
        
        Vector2 dir = new Vector2(xRaw, yRaw).normalized;
        // if (downPressed) crouch();
        // else stopCrouch();
        if (!isDashing && canWalk)
        {
            if (onGround)   Walk(dir);
            else AirWalk(dir);
        }
        if (dashPressed || isDashing) Dash();
        if (onWallSlide) wallSlide();
        if (wallJumpPressed) wallJump();
        if (dashJumpPressed) dashJump();
        else if (jumpPressed)Jump(dir);
        else if (airJumpPressed) airJump(dir);
        
        
    }

    void changeMoveModel(int MMIndex)
    {
        if (this.moveModel == MMIndex) return;
        this.moveModel = MMIndex;
        transformTImeCounter = transformTime;
        StartCoroutine(stopMove(transformTime));    //è½¬å˜æ¨¡å¼çš„æ—¶å€™ä¸ç»™åŠ¨ï¼Ÿ
    }

    //TODO:è¹²ä¸‹çš„è§¦å‘ï¼Œç»´ç³»å’Œè§£é™¤ï¼Œæˆ‘è§‰å¾—è¿™æ ·å†™ä¸è¡Œ
    //TODO:v2
    void crouch()
    {
        transform.localScale = new Vector3(0.8f,0.8f/4*3,1f);
        downPressed = true;
    }

    void stopCrouch()
    {
        transform.localScale = new Vector3(0.8f,0.8f,1f);
        downPressed = false;
    }

    void OnTriggerStay2D(Collider2D other) {
        //ä¸åœ¨æ— æ•Œæ—¶é—´å†…çš„è¯
        if (!this.hurtTP.BeforeTime())
        {
            if(other.gameObject.tag=="HurtArea")
            {
                Debug.Log("enter HurtArea!");
                health--;
                hurtTP.MarkPoint();
                MyInpulse.GenerateImpulse(new Vector3(2,5,0));
            }  
        }

    }     

    void wallJump()
    {
        side = onRightWall? -1:1;
        Vector2 dir = new Vector2(side, 2).normalized;
        // Debug.Log(dir);
        rb.velocity = dir * wallJumpSpeed;
        wallJumpPressed = false;
        StartCoroutine(stopMove(0.1f));
    }

    // void OnCollisionEnter2D(Collision2D other) {
    //     Debug.Log(other.gameObject.name);    
    // }

    void wallSlide()
    {
        
        rb.velocity = new Vector2(rb.velocity.x, -wallSlideSpeed);
    }

    void chekGround()
    {
        // RaycastHit2D groundHit1 = Physics2D.Raycast(new Vector3(transform.position.x - spSize.x/4, transform.position.y, transform.position.z), -transform.up, spSize.y/2 + 0.1f, groundLayer); 
        // RaycastHit2D groundHit2 = Physics2D.Raycast(new Vector3(transform.position.x + spSize.x/4, transform.position.y, transform.position.z), -transform.up, spSize.y/2 + 0.1f, groundLayer);
        MyRaycast rc1 = new MyRaycast(new Vector3(transform.position.x - spSize.x/4, transform.position.y, transform.position.z), -transform.up, spSize.y/2 + 0.1f, groundLayer);
        MyRaycast rc2 = new MyRaycast(new Vector3(transform.position.x + spSize.x/4, transform.position.y, transform.position.z), -transform.up, spSize.y/2 + 0.1f, groundLayer);
        RaycastHit2D groundHit1 = rc1.GetRaycastHit2D();
        RaycastHit2D groundHit2 = rc2.GetRaycastHit2D();
        // rc1.DrawRaycast2D(Color.red);
        // rc2.DrawRaycast2D(Color.red);
        //ç”»çš„å°„çº¿åªåœ¨Sceneçª—å£çœ‹å¾—è§
        if ( groundHit1.collider != null || groundHit2.collider != null)
        {
            onGround = true;SM.SetTrue("onGround");
            isJumping = false;  
            onAir = false;SM.SetFalse("onAir");
            onWall = false;
            onWallSlide = false;
            jumpTimeCounter = jumpTime;
            graceTimeCounter = graceTime;
            airJumpCounter=1;
        }
        else
        {
            onGround = false;SM.SetFalse("onGround");
            onAir = true;SM.SetTrue("onAir");
            graceTimeCounter -= Time.deltaTime;
        }
        
    }   

    void checkWall()
    {   
        //onwalléœ€è¦æ–¹å‘é”®è¾“å…¥å—ï¼Ÿ
        if (onRightWall = Physics2D.Raycast(new Vector3(transform.position.x, transform.position.y + spSize.y/4, transform.position.z), Vector3.right, spSize.x/2 + 0.1f, groundLayer)
            ||  Physics2D.Raycast(new Vector3(transform.position.x, transform.position.y - spSize.y/4, transform.position.z), Vector3.right, spSize.x/2 + 0.1f, groundLayer)){}
        else
        {
            onLeftWall = Physics2D.Raycast(new Vector3(transform.position.x, transform.position.y + spSize.y/4, transform.position.z), Vector3.left, spSize.x/2 + 0.1f, groundLayer)
            ||  Physics2D.Raycast(new Vector3(transform.position.x, transform.position.y- spSize.y/4, transform.position.z), Vector3.left, spSize.x/2 + 0.1f, groundLayer);
        }
        // Debug.DrawRay(new Vector3(transform.position.x, transform.position.y + spSize.y/4, transform.position.z), Vector3.left*(spSize.x/2 + 0.1f), Color.red);
        // Debug.DrawRay(new Vector3(transform.position.x, transform.position.y- spSize.y/4, transform.position.z), Vector3.left*(spSize.x/2 + 0.1f), Color.red);
        // Debug.DrawRay(new Vector3(transform.position.x, transform.position.y + spSize.y/4, transform.position.z), Vector3.right*(spSize.x/2 + 0.1f), Color.red);
        // Debug.DrawRay(new Vector3(transform.position.x, transform.position.y- spSize.y/4, transform.position.z), Vector3.right*(spSize.x/2 + 0.1f), Color.red);
        if (onWall = onRightWall || onLeftWall)airJumpCounter=1;
        // {higherJump = false;
        // isJumping = false;}
    }

    void Walk(Vector2 dir)
    {
        // if (dir.x !=0 || dir.y != 0)rb.velocity = new Vector2(dir.x * speed, rb.velocity.y);    //å³æœ‰æ–¹å‘è¾“å…¥æ‰ä¼šwalkï¼Œé¿å…ä¸è¾“å…¥æ—¶å°†é€Ÿåº¦å½’é›¶
        if (dir.x !=0 || dir.y != 0)rb.velocity = new Vector2(dir.x * speed, rb.velocity.y);    //å³æœ‰æ–¹å‘è¾“å…¥æ‰ä¼šwalkï¼Œé¿å…ä¸è¾“å…¥æ—¶å°†é€Ÿåº¦å½’é›¶
        else {if(onGround)rb.velocity=new Vector2(0,0);}    //åœ°é¢ï¼Œæ— æ–¹å‘è¾“å…¥ï¼Œç«‹å³åœä¸‹
    }

    void AirWalk(Vector2 dir)
    {
        if (rb.velocity.x < 11)
        {
            if (dir.x !=0)rb.velocity = new Vector2(dir.x * airWalkSpeed, rb.velocity.y);    //å³æœ‰æ–¹å‘è¾“å…¥æ‰ä¼šwalkï¼Œé¿å…ä¸è¾“å…¥æ—¶å°†é€Ÿåº¦å½’é›¶
        }
    }


    /*
    è·³è·ƒ
    è·³è·ƒæ¡ä»¶åˆ¤æ–­
    è·³è·ƒåŠ¨ä½œ
    è·³è·ƒæ¡ä»¶é‡ç½®
    */
    void Jump(Vector2 dir)
    {
        rb.velocity = new Vector2(rb.velocity.x, jumpForce);
        jumpPressed = false;
    }

    //ç›®å‰çš„åŸç†
    //dashPressedæˆ–è€…isDashingéƒ½ä¼šè¿›å…¥Dash
    //dashPressedè¿›å…¥æ—¶ä»¤dashPressedä¸ºfalseï¼Œç„¶åå¼€å¯0.1fçš„åç¨‹ä¿è¯isDash=trueï¼Œ
    //ä¸¤è€…éƒ½ä¼šè®¾ç½®é«˜çš„é€Ÿåº¦å€¼
    void Dash()
    {       
        // rb.velocity = dir * dashSpeed;
        if (dashPressed)
        {
            dashPressed = false;
            transform.localScale = new Vector3(transform.localScale.x, transform.localScale.y/4*3,transform.localScale.z);
            StartCoroutine(DashWait());
        }
        rb.velocity = new Vector2(side*dashSpeed,0);  
    }

    void airJump(Vector2 dir)
    {
        rb.velocity = new Vector2(rb.velocity.x, airJumpForce);
        airJumpPressed=false;
    }

    void dashJump()
    {
        rb.gravityScale = originalGravity;
        isDashing = false;SM.SetFalse("isDashing");
        rb.velocity = new Vector2(side*speed, rb.velocity.y);
        transform.localScale = new Vector3(0.8f,0.8f,1f);
        if (downPressed)
        {
            rb.velocity = new Vector2(dashSpeed*side/5*4, dashJumpForce);
        }
        else
        {
            rb.velocity = new Vector2(dashSpeed*side/5*3, dashJumpForce);
        }
        StartCoroutine(stopMove(0.3f));   //ç›®å‰çš„dashJumpä¸€å°æ®µæ—¶é—´ä¸å…è®¸é€šè¿‡æ–¹å‘é”®å¯¹é€Ÿåº¦è°ƒèŠ‚
                                        //TODO:æœ€å¥½æ˜¯è°ƒèŠ‚èƒ½åŠ›é€æ­¥å›å¤åˆ°æ­£å¸¸
        // StartCoroutine(airMoveLimit(0.3f));  
        //ä¸¤ä¸ªçº¿æ€§æ’å€¼å¯èƒ½å¯ä»¥ï¼Ÿ
        //å¦‚æœä¸€å†²å°±æ’å¢™ï¼Œè¿™æ—¶å€™å´è¿˜æ˜¯å†²åˆºæ—¶çš„å—æŸç©ºä¸­ç§»é€Ÿ
        //æ‰€ä»¥è¦åšå‡ºç°æ„å¤–è¦ç›´æ¥å°†airWalkSpeedæ­£å¸¸çš„åˆ¤æ–­ã€‚æˆ–è€…ç¼©çŸ­å—æŸåˆ°è¾¾æ­£å¸¸çš„é€Ÿåº¦ï¼Ÿ
        //æ„å¤–ï¼šå—å‡»ï¼Ÿæ’å¢™ï¼Ÿ
        //æˆ–è€…ä¸è¦å†²åˆºè·³è·ƒäº†
        dashJumpPressed = false;
    }

    void chop()
    {
        // transform.GetChild(0).gameObject.SetActive(true);
    }

    // void upChop()
    // {
    //     Debug.Log("ä¸ŠæŒ‘");
    //     transform.GetChild(0).gameObject.SetActive(true);
    //     StartCoroutine(upChopWait(0.25f));
    //     rb.velocity = new Vector2(0, 20f);
    // }


    IEnumerator DashWait()  //å†²åˆºæœŸé—´
    {
        isDashing = true;SM.SetTrue("isDashing");
        canWalk = false;
        rb.gravityScale = 0;
        yield return new WaitForSeconds(.1f);
        if (isDashing)
        {
        rb.gravityScale = originalGravity;
        isDashing = false;SM.SetFalse("isDashing");
        rb.velocity = new Vector2(side*speed, rb.velocity.y);
        transform.localScale = new Vector3(0.8f,0.8f,1f);
        canWalk = true;
        }
    }

    //  IEnumerator airMoveLimit(float time)    //å—æŸç©ºç§»æ¢å¤
    // {
    //     int temp = this.airWalkSpeed;
    //     this.airWalkSpeed = Mathf.Lerp(0, temp, Mathf.lerp(0, 1));
    //     yield return new WaitForSeconds(time);
    // }

    IEnumerator stopMove(float time)    //ä¸å‡†ç§»åŠ¨
    {
        canWalk = false;
        yield return new WaitForSeconds(time);
        canWalk = true;
    }

    IEnumerator stopDash(float time)    //ä¸å‡†å†²åˆº
    {
        hasDash = true;
        yield return new WaitForSeconds(time);
        hasDash = false;
    }

    // IEnumerator upChopWait(float time)
    // {
    //     isUpChoping = true;
    //     yield return new WaitForSeconds(time);
    //     isUpChoping = false;
    // }

    void OnGUI()  
    {  
        GUI.TextArea(new Rect(0, 0, 250, 40), "Health " + health);//ä½¿ç”¨GUIåœ¨å±å¹•ä¸Šé¢å®æ—¶æ‰“å°å½“å‰æŒ‰ä¸‹çš„æŒ‰é”®  
    }  
}
